MediWeb/Controllers/FullDetailsController.cs
using MediWeb.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediWeb.Models;
using System.IO;

namespace MediWeb.ViewModel
{
    public class FullDetailsController : Controller
    {
        //
        // GET: /FullDetails/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult addPatient()
        {
            patientRepository prp = new patientRepository();
            List<SelectListItem> dbAllergyList = prp.getAllergyItems();
            List<SelectListItem> dbMedicineList = prp.getMedicineItems();
            List<SelectListItem> dbTestList = prp.getTestItems();
            List<SelectListItem> dbDoctorList = prp.getDoctorItems();
            //List<SelectListItem> gender = new List<SelectListItem>(
            //                                {
            //                                new SelectListItem { Text = "Male", Value = "M" },
            //                                new SelectListItem { Text = "Female", Value = "F" }
            //                                }, "Value" , "Text");
            ViewBag.allergies = dbAllergyList;
            ViewBag.medicine = dbMedicineList;
            ViewBag.test = dbTestList;
            ViewBag.doctor = dbDoctorList;

            return View();
        }

        [HttpPost]
        public ActionResult addPatient(FullDetails ptnt)
        {
            patientRepository pr = new patientRepository();
            ptnt.patient.photo = "none.jpg";
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var filename = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads"), filename);
                    file.SaveAs(path);

                    ptnt.patient.photo = filename; //getting image
                }

            }

            string allergies = Request["allergies"].ToString();
            //string allergyID = Request["allergyID"].ToString();
            string allergyDate = Request["allergyDate"].ToString();

            System.Diagnostics.Debug.Print("allergies=" + allergies);
            System.Diagnostics.Debug.Print("Name: " + ptnt.patient.name);

            string[] allergiesList = allergies.Split(',');
            System.Diagnostics.Debug.Print("allergy: " + allergiesList[0]);
            //string[] allergyIDList = allergyID.Split(',');

            string[] allergyDateList = allergyDate.Split(',');

            for (int i = 0; i < allergiesList.Length; i++)
            {
                Allergies a = new Allergies();
                a.AID = Convert.ToString(allergiesList[i]);
                //a.allergyType = Convert.ToString(allergiesList[i]);
                if (String.IsNullOrWhiteSpace(a.AID))
                {
                    continue;
                }
                System.Diagnostics.Debug.Print("ID=" + a.AID);
                ptnt.allergy.Add(a);
                ptnt.allergyDate.Add(allergyDateList[i]);
            }

            string problem = Request["problem"].ToString();

            string problemDate = Request["problemDate"].ToString();

            System.Diagnostics.Debug.Print("problems=" + allergies);


            string[] problemList = problem.Split(',');
            System.Diagnostics.Debug.Print("problem: " + problemList[0]);
            //string[] allergyIDList = allergyID.Split(',');

            string[] problemDateList = problemDate.Split(',');

            for (int i = 0; i < problemList.Length; i++)
            {
                if (String.IsNullOrWhiteSpace(problemList[i]))
                {
                    continue;
                }
                System.Diagnostics.Debug.Print("problem=" + problemList[i]);
                ptnt.problem.Add(problemList[i]);
                ptnt.problemDate.Add(problemDateList[i]);
            }

            string medicinename = Request["medicine"].ToString();
            //string medicineID = Request["medicineID"].ToString();
            string prescriptionDate = Request["prescriptionDate"].ToString();
            //string prescriptionByDID = Request["prescribedByDID"].ToString();
            string prescriptionBy = Request["doctor"].ToString();

            string[] medicineList = medicinename.Split(',');
            //string[] medicineIDList = medicineID.Split(',');
            string[] medicineDateList = prescriptionDate.Split(',');
            //string[] prescribedByListDID = prescriptionBy.Split(',');
            string[] doctorList = prescriptionBy.Split(',');

            for (int i = 0; i < medicineList.Length; i++)
            {
                Medicine m = new Medicine();
                m.MID = Convert.ToString(medicineList[i]);
                //m.medicineName = Convert.ToString(medicineList[i]);
                if (String.IsNullOrWhiteSpace(m.MID))
                {
                    continue;
                }
                ptnt.medicine.Add(m);
                ptnt.prescriptionDate.Add(medicineDateList[i]);
                Doctor d = new Doctor();
                d.DID = doctorList[i];
                //d.doctorName = prescribedByList[i];
                ptnt.prescribedBy.Add(d);
            }

            string testname = Request["test"].ToString();
            //string testID = Request["testID"].ToString();
            string testDate = Request["testDate"].ToString();
            string testReadings = Request["testReadings"].ToString();

            string[] testList = testname.Split(',');
            //string[] testIDList = testID.Split(',');
            string[] testDateList = testDate.Split(',');
            string[] testReadingsList = testReadings.Split(',');
            for (int i = 0; i < testList.Length; i++)
            {
                Test t = new Test();
                t.TID = Convert.ToString(testList[i]);
                //t.testName = Convert.ToString(testList[i]);
                if (String.IsNullOrWhiteSpace(t.TID))
                {
                    continue;
                }
                ptnt.test.Add(t);
                ptnt.testDate.Add(testDateList[i]);
                ptnt.testReadings.Add(testReadingsList[i]);
            }


            pr.addPatient(ptnt);
            return View("patientAdded", ptnt);
        }

        //public ActionResult viewSearch()
        //{
        //    return View();
        //}

        [Authorize]
        public ActionResult viewSearch(string pid)
        {

            string str = pid;
            //Request["ptntSearch"].ToString();
            System.Diagnostics.Debug.Print("" + str);
            patientRepository pr = new patientRepository();
            FullDetails p = pr.viewSearch(str);

            return View("viewSearchDetails", p);
        }

        //[HttpPost]
        //public ActionResult viewSearch(string a)
        //{

        //    string str = Request["ptntSearch"].ToString();
        //    System.Diagnostics.Debug.Print("" + str);
        //    patientRepository pr = new patientRepository();
        //    FullDetails p = pr.viewSearch(str);

        //    return View("viewSearchDetails", p);
        //}

        [Authorize]
        public ActionResult edit(string id)
        {
            patientRepository prp = new patientRepository();
            FullDetails p = prp.viewSearch(id);
            List<SelectListItem> dbAllergyList = prp.getAllergyItems();
            List<SelectListItem> dbMedicineList = prp.getMedicineItems();
            List<SelectListItem> dbTestList = prp.getTestItems();
            List<SelectListItem> dbDoctorList = prp.getDoctorItems();
            ViewBag.allergies = dbAllergyList;
            ViewBag.medicine = dbMedicineList;
            ViewBag.test = dbTestList;
            ViewBag.doctor = dbDoctorList;


            return View(p);
        }

        [Authorize]
        [HttpPost]
        public ActionResult edit(FullDetails ptnt)
        {
            System.Diagnostics.Debug.Print("" + ptnt.patient.name);
            string allergies = Request["allergies"].ToString();
            //string allergyID = Request["allergyID"].ToString();
            string allergyDate = Request["allergyDate"].ToString();

            System.Diagnostics.Debug.Print("allergies=" + allergies);
            System.Diagnostics.Debug.Print("Name: " + ptnt.patient.name);

            string[] allergiesList = allergies.Split(',');
            System.Diagnostics.Debug.Print("allergy: " + allergiesList[0]);
            //string[] allergyIDList = allergyID.Split(',');

            string[] allergyDateList = allergyDate.Split(',');

            for (int i = 0; i < allergiesList.Length; i++)
            {
                Allergies a = new Allergies();
                a.AID = Convert.ToString(allergiesList[i]);
                //a.allergyType = Convert.ToString(allergiesList[i]);
                if (String.IsNullOrWhiteSpace(a.AID))
                {
                    continue;
                }
                System.Diagnostics.Debug.Print("ID=" + a.AID);
                ptnt.allergy.Add(a);
                ptnt.allergyDate.Add(allergyDateList[i]);
            }

            string problem = Request["problem"].ToString();

            string problemDate = Request["problemDate"].ToString();

            System.Diagnostics.Debug.Print("problems=" + allergies);


            string[] problemList = problem.Split(',');
            System.Diagnostics.Debug.Print("problem: " + problemList[0]);
            //string[] allergyIDList = allergyID.Split(',');

            string[] problemDateList = problemDate.Split(',');

            for (int i = 0; i < problemList.Length; i++)
            {
                if (String.IsNullOrWhiteSpace(problemList[i]))
                {
                    continue;
                }

MediWeb/Views/FullDetails/addNew.cshtml
@model MediWeb.ViewModel.FullDetails

@{
    ViewBag.Title = "addNew";
}

<h2>addNew</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enter Details Of Patients</h4>
        <hr />
        @Html.ValidationSummary(true)

         <div class="form-group">
            @Html.LabelFor(model => model.patient.PID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.PID)
                @Html.ValidationMessageFor(model =>  model.patient.PID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.name)
                @Html.ValidationMessageFor(model =>  model.patient.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.DOB, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.DOB)
                @Html.ValidationMessageFor(model =>  model.patient.DOB)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.gender, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.gender)
                @Html.ValidationMessageFor(model =>  model.patient.gender)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.address)
                @Html.ValidationMessageFor(model =>  model.patient.address)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.phone)
                @Html.ValidationMessageFor(model =>  model.patient.phone)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.marritalStatus, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.marritalStatus)
                @Html.ValidationMessageFor(model =>  model.patient.marritalStatus)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.bloodGroup, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.bloodGroup)
                @Html.ValidationMessageFor(model =>  model.patient.bloodGroup)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.fatherName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.fatherName)
                @Html.ValidationMessageFor(model =>  model.patient.fatherName)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.occupation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.occupation)
                @Html.ValidationMessageFor(model =>  model.patient.occupation)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.height, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.height)
                @Html.ValidationMessageFor(model =>  model.patient.height)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.patient.weight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.weight)
                @Html.ValidationMessageFor(model =>  model.patient.weight)
            </div>
        </div>

        <h3> Enter the Allergies you have:</h3>

        <div class="form-group">
            @Html.LabelFor(model => model.allergies.AID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.allergies.AID)
                @Html.ValidationMessageFor(model =>  model.allergies.AID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.allergies.allergyType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.allergies.allergyType)
                @Html.ValidationMessageFor(model =>  model.allergies.allergyType)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.dateOfAllergy, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateOfAllergy)
                @Html.ValidationMessageFor(model =>  model.dateOfAllergy)
            </div>
        </div>
        <h3>Enter your Current Prescription: </h3><hr />
        <div class="form-group">
            @Html.LabelFor(model => model.medicine.MID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.medicine.MID)
                @Html.ValidationMessageFor(model =>  model.medicine.MID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.medicine.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.medicine.name)
                @Html.ValidationMessageFor(model =>  model.medicine.name)
            </div>
        </div>
        <h4>Prescibed by:</h4>
        <div class="form-group">
            @Html.LabelFor(model => model.doctor.DID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.doctor.DID)
                @Html.ValidationMessageFor(model =>  model.doctor.DID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.doctor.doctorName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.doctor.doctorName)
                @Html.ValidationMessageFor(model =>  model.doctor.doctorName)
            </div>
        </div>

        <h3>Enter the medical tests you have taken:</h3>

         <div class="form-group">
            @Html.LabelFor(model => model.test.TID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.test.TID)
                @Html.ValidationMessageFor(model =>  model.test.TID)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.test.testName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.test.testName)
                @Html.ValidationMessageFor(model =>  model.test.testName)
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.dateOfTest, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateOfTest)
                @Html.ValidationMessageFor(model =>  model.dateOfTest)
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MediWeb/Views/FullDetails/addPatient.cshtml
@model MediWeb.ViewModel.FullDetails

@{
    ViewBag.Title = "addNew";
}
<style>
    th, td {
        border: 2px solid black;
    }

    table {
        width: 100%;
    }

    input.tableInput {
        width: 100%;
    }


    span.addRow {
        position: absolute;
        float: right;
        padding: 4px;
        margin: 4px;
        border-radius: 3px;
        border: 1px solid #ccc;
    }

        span.addRow:hover {
            background-color: #eee;
            cursor: pointer;
        }
</style>

@using (Html.BeginForm("addPatient", "FullDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Enter Details Of Patients</h3>
        <hr />
        @Html.ValidationSummary(true)

        @*<div class="form-group">
            @Html.LabelFor(model => model.patient.PID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.PID)
                @Html.ValidationMessageFor(model => model.patient.PID)
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.patient.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.name)
                @Html.ValidationMessageFor(model => model.patient.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.DOB, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.DOB)
                @Html.ValidationMessageFor(model => model.patient.DOB)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.gender, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
    var selectList1 = new SelectList(
       new List<SelectListItem>
                   {
                   new SelectListItem {Text = "Male", Value = "M"},
                    new SelectListItem {Text = "Female", Value = "F"},
                    new SelectListItem {Text = "Unknown", Value = "U"}
                    }, "Value", "Text");
                }
                @Html.DropDownListFor(model => model.patient.gender, selectList1, "Select Gender", null)
                @*@Html.EditorFor(model => model.patient.gender)*@
                @Html.ValidationMessageFor(model => model.patient.gender)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.address)
                @Html.ValidationMessageFor(model => model.patient.address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.phone)
                @Html.ValidationMessageFor(model => model.patient.phone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.marritalStatus, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @{
    var selectList2 = new SelectList(
       new List<SelectListItem>
                   {
                   new SelectListItem {Text = "Single", Value = "Single"},
                    new SelectListItem {Text = "Married", Value = "Married"}
                    }, "Value", "Text");
                }
                @Html.DropDownListFor(model => model.patient.marritalStatus, selectList2, "Select Gender", null)
                @* @Html.EditorFor(model => model.patient.marritalStatus)*@
                @Html.ValidationMessageFor(model => model.patient.marritalStatus)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.bloodGroup, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
    var selectList3 = new SelectList(
       new List<SelectListItem>
                   {
                   new SelectListItem {Text = "A+", Value = "A+"},
                    new SelectListItem {Text = "B+", Value = "B+"}
                    }, "Value", "Text");
                }
                @Html.DropDownListFor(model => model.patient.bloodGroup, selectList3, "Select Gender", null)
                @* @Html.EditorFor(model => model.patient.bloodGroup)*@
                @Html.ValidationMessageFor(model => model.patient.bloodGroup)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.fatherName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.fatherName)
                @Html.ValidationMessageFor(model => model.patient.fatherName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.occupation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.occupation)
                @Html.ValidationMessageFor(model => model.patient.occupation)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.height, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.height)
                @Html.ValidationMessageFor(model => model.patient.height)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.weight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.weight)
                @Html.ValidationMessageFor(model => model.patient.weight)
            </div>
        </div>
        
         <div class="form-group">
            @Html.LabelFor(model => model.user.password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user.password)
                @Html.ValidationMessageFor(model => model.user.password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.photo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" />
            </div>
        </div>
        <br />
        <br />
        <hr />


        <div class="form-group">
            <h3>Enter the Allergies you have:</h3>
            <hr />
            <div class="col-md-10">
                <table id="allergy">
                    <tr>
                        @*<th>Allergy ID</th>*@
                        <th>Allergy Type</th>
                        <th>Date Of Allergy</th>
                    </tr>
                    <tr class="allergyItems">
                        @*<td><input type="text" name="allergyID" class="tableInput" /></td>*@
                        <td>@Html.DropDownList("allergies", "Select allergy type")</td>
                        <td>
                            <input type="text" name="allergyDate" class="tableInput" /></td>
                    </tr>
                </table>
                <span id="addAllergy" class="addRow">Add Row</span>
            </div>
        </div>
        <br />
        <br />
        <hr />
        <div class="form-group">
            <h3>Enter the problems you have </h3>
            <div class="col-md-10">
                <table id="problem">
                    <tr>
                        <th>Problem</th>
                        <th>Problem Date</th>
                    </tr>
                    <tr class="problemItems">
                        <td>
                            <input type="text" name="problem" class="tableInput" /></td>
                        <td>
                            <input type="text" name="problemDate" class="tableInput" /></td>
                    </tr>
                </table>
                <span id="addProblem" class="addRow">Add Row</span>
            </div>
        </div>
        <br />
        <br />
        <hr />





        <div class="form-group">
            <h3>Enter your Current Prescription: </h3>
            <div class="col-md-10">
                <table id="medicine">
                    <tr>
                        <th>Medicine Name</th>
                        <th>Prescription Date</th>
                        <th>Prescribed By (Doctor)</th>
                    </tr>
                    <tr class="medicineItems">
                        <td>@Html.DropDownList("medicine", "Select medicine")</td>
                        <td>
                            <input type="text" name="prescriptionDate" class="tableInput" /></td>
                        <td>@Html.DropDownList("doctor", "Select Doctor")</td>
                    </tr>
                </table>
                <span id="addMedicine" class="addRow">Add Row</span>
            </div>
        </div>
        <br />
        <br />
        <hr />


        <div class="form-group">
            <h3>Enter the medical tests you have taken:</h3>
            <hr />
            <div class="col-md-10">
                <table id="test">
                    <tr>
                        <th>Test Name</th>
                        <th>date Of Test</th>
                        <th>Test Result/ Readings</th>
                    </tr>
                    <tr class="testItems">
                        <td>@Html.DropDownList("test", "Select test you took")</td>
                        <td>
                            <input type="text" name="testDate" class="tableInput" /></td>
                        <td>
                            <input type="text" name="testReadings" class="tableInput" /></td>
                    </tr>
                </table>
                <span id="addTest" class="addRow">Add Row</span>
            </div>
        </div>


        <br />
        <hr />

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Add patient" id="addPatient" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    
    $("#addAllergy").on('click', function () {
        $(".allergyItems:first").clone().appendTo("table#allergy");
        
    });

    $("#addProblem").on('click', function () {
        $(".problemItems:first").clone().appendTo("table#problem");

    });

    $("#addMedicine").on('click', function () {
        $(".medicineItems:first").clone().appendTo("table#Medicine");

    });

    $("#addTest").on('click', function () {
        $(".testItems:first").clone().appendTo("table#test");

    });
    @*$("#addProblem").on('click', function () {
        $("table#problem").append('<tr><td><input type="text" name="problem" class="tableInput"/></td><td><input type="text" name="problemDate" class="tableInput"/></td></tr>');

    });

    $("#addMedicine").on('click', function () {
        $("table#medicine").append("<tr><td>@Html.DropDownList("medicine", "Select medicine")</td><td><input type='text' name='prescriptionDate' class='tableInput'/></td><td>fgfd@Html.DropDownList("doctor", "Select Doctor")</td></tr>");
    });

    $("#addTest").on('click', function () {
        $("table#test").append("<tr><td>@Html.DropDownList("test", "Select test you took")</td><td><input type='text' name='testDate' class='tableInput'/></td><td><input type='text' name='testReadings' class='tableInput'/></td></tr>");
    });*@
</script>

MediWeb/Views/FullDetails/addPatient2.cshtml
@model MediWeb.ViewModel.FullDetails

@{
    ViewBag.Title = "addPatient";
}

<h2>addPatient</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FullDetails</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.patient.PID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.PID)
                @Html.ValidationMessageFor(model => model.patient.PID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.patient.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patient.name)
                @Html.ValidationMessageFor(model => model.patient.name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>